[versions]
androidGradlePlugin = "8.2.0"

kotlin = "1.9.20"
ksp = "1.9.20-1.0.14"

opencv = "4.9.0"

apache-commons-io = "2.4"
github-requery-sqlite-android = "3.43.0"
acra = "5.11.3"
threetenabp = "1.4.6"
compose-richtext = "0.17.0"
github-jvziyaoyao-scale = "1.1.0-alpha.4"
github-cheonjaeung-gridlayout = "2.0.0"
compose-settings = "2.3.0"

junit = "4.13.2"

dependencyAnalysis = "1.32.0"


[libraries]
kotlinx-serialization = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version = "1.6.0" }

opencv = { module = "org.opencv:opencv", version.ref = "opencv" }
protobuf-protobufJavalite = { module = "com.google.protobuf:protobuf-javalite", version = "3.21.12" }

apache-commons-io = { module = "org.apache.directory.studio:org.apache.commons.io", version.ref = "apache-commons-io" }
github-requery-sqlite-android = { module = "com.github.requery:sqlite-android", version.ref = "github-requery-sqlite-android" }
acra-http = { module = "ch.acra:acra-http", version.ref = "acra" }
acra-dialog = { module = "ch.acra:acra-dialog", version.ref = "acra" }
threetenabp = { module = "com.jakewharton.threetenabp:threetenabp", version.ref = "threetenabp" }
compose-richtext-commonmark = { module = "com.halilibo.compose-richtext:richtext-commonmark", version.ref = "compose-richtext" }
compose-richtext-ui-material3 = { module = "com.halilibo.compose-richtext:richtext-ui-material3", version.ref = "compose-richtext" }
github-jvziyaoyao-scale-imageViewer = { module = "com.jvziyaoyao.scale:image-viewer", version.ref = "github-jvziyaoyao-scale" }
github-cheonjaeung-gridlayout = { module = "com.cheonjaeung.compose.grid:grid", version.ref = "github-cheonjaeung-gridlayout" }
com-github-alorma-composeSettings-ui = { group = "com.github.alorma.compose-settings", name = "ui-tiles", version.ref = "compose-settings" }
com-github-alorma-composeSettings-ui-extended = { group = "com.github.alorma.compose-settings", name = "ui-tiles-extended", version.ref = "compose-settings" }

junit = { module = "junit:junit", version.ref = "junit" }


[plugins]
android-application = { id = "com.android.application", version.ref = "androidGradlePlugin" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-plugin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }

ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
protobuf = { id = "com.google.protobuf", version = "0.9.4" }

secrets-gradle-plugin = { id = "com.google.android.libraries.mapsplatform.secrets-gradle-plugin", version = "2.0.1" }
android-library = { id = "com.android.library", version.ref = "androidGradlePlugin" }
androidGitVersion = { id = "com.gladed.androidgitversion", version = "0.4.14" }

dependencyAnalysis = { id = "com.autonomousapps.dependency-analysis", version.ref = "dependencyAnalysis" }
